/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.beans.BeansUsuario;
import modeloDAO.DaoUsuario;

/**
 *
 * @author PC
 */
public class FormUsuario extends javax.swing.JFrame {

    /**
     * Creates new form FormUsuario
     */
    public FormUsuario() {
        initComponents();
        listarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalvar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();
        jButtonCarCampos = new javax.swing.JButton();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButtonPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(20, 20, 90, 30);

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlterar);
        jButtonAlterar.setBounds(20, 53, 90, 30);

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(20, 90, 90, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cod:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 30, 30, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Usuário");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 60, 50, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Senha");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 100, 50, 20);
        getContentPane().add(jTextFieldCod);
        jTextFieldCod.setBounds(210, 20, 80, 30);

        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsuario);
        jTextFieldUsuario.setBounds(210, 60, 320, 30);
        getContentPane().add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(210, 100, 220, 30);

        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Usuario", "Senha", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(jTableUsuarios);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 290, 690, 210);

        jButtonCarCampos.setText("Carregar Campos");
        jButtonCarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarCamposActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCarCampos);
        jButtonCarCampos.setBounds(10, 180, 150, 30);

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Administrador", "Recepcionista", "Médico" }));
        getContentPane().add(jComboBoxTipo);
        jComboBoxTipo.setBounds(260, 160, 140, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tipo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 160, 50, 17);

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(10, 140, 120, 30);

        setSize(new java.awt.Dimension(764, 555));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        BeansUsuario usu = new BeansUsuario();
        usu.setCodUsuario(Integer.parseInt(jTextFieldCod.getText()));
        usu.setNomeUsuario(jTextFieldUsuario.getText());
        usu.setSenhaUsuario(jPasswordFieldSenha.getText());
        usu.setTipo((String) jComboBoxTipo.getSelectedItem());
       
        DaoUsuario usuDao = new DaoUsuario();
        usuDao.salvar(usu);
        JOptionPane.showMessageDialog(this, "Salvo");
        
        listarTabela();
        limparCampos();
            
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        BeansUsuario usu = new BeansUsuario();
        usu.setCodUsuario(Integer.parseInt(jTextFieldCod.getText()));
        usu.setNomeUsuario(jTextFieldUsuario.getText());
        usu.setSenhaUsuario(jPasswordFieldSenha.getText());
         usu.setTipo((String) jComboBoxTipo.getSelectedItem());
       
        DaoUsuario usuDao = new DaoUsuario();
        usuDao.alterar(usu);
        JOptionPane.showMessageDialog(this, "Alterado");
        
        listarTabela();
        limparCampos();
        
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
       int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir??", "Confirma Exclusão", JOptionPane.YES_NO_OPTION);
        
       if (resposta == 0) {
        BeansUsuario usu = new BeansUsuario();
        usu.setCodUsuario(Integer.parseInt(jTextFieldCod.getText()));
       
        DaoUsuario usuDao = new DaoUsuario();
        usuDao.excluir(usu);
        JOptionPane.showMessageDialog(this, "Deletado");
       }
       listarTabela();
       
       limparCampos();
       
       
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonCarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarCamposActionPerformed
        CarregarCampos();
    }//GEN-LAST:event_jButtonCarCamposActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
       String nome = jTextFieldUsuario.getText();
       this.listarTabelaNomes(nome);
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    public void listarTabela(){
      
       DefaultTableModel val = (DefaultTableModel) jTableUsuarios.getModel();
       val.getDataVector().removeAllElements();
       DaoUsuario usuDao = new DaoUsuario();
       List <BeansUsuario> usuario = usuDao.listarUsuarios();
       int i = 0;
       while(usuario.size() > i){
           
       val.addRow(new Object[] {usuario.get(i).getCodUsuario(),  usuario.get(i).getNomeUsuario(), usuario.get(i).getSenhaUsuario(), usuario.get(i).getTipo()});
       i++;
       }
    } 
    
    public void listarTabelaNomes(String nome){
      
       DefaultTableModel val = (DefaultTableModel) jTableUsuarios.getModel();
       val.getDataVector().removeAllElements();
       DaoUsuario usuDao = new DaoUsuario();
       List <BeansUsuario> usuario = usuDao.pesquisarUsuarios(nome);
       int i = 0;
       while(usuario.size() > i){
           
       val.addRow(new Object[] {usuario.get(i).getCodUsuario(),  usuario.get(i).getNomeUsuario(), usuario.get(i).getSenhaUsuario(), usuario.get(i).getTipo()});
       i++;
       }
    }
    
    public void CarregarCampos(){
        int setar = jTableUsuarios.getSelectedRow();
        
        jTextFieldCod.setText(jTableUsuarios.getModel().getValueAt(setar, 0).toString());
        jTextFieldUsuario.setText(jTableUsuarios.getModel().getValueAt(setar, 1).toString());
        jPasswordFieldSenha.setText(jTableUsuarios.getModel().getValueAt(setar, 2).toString());
        jComboBoxTipo.setSelectedItem(jTableUsuarios.getModel().getValueAt(setar, 3).toString());
            
    }
     public void limparCampos(){
        jTextFieldCod.setText("");
        jTextFieldUsuario.setText("");
        jPasswordFieldSenha.setText("");
        jComboBoxTipo.setSelectedItem("Selecione");
    } 
     
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCarCampos;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuarios;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
