/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import java.sql.Connection;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.beans.BeansProntuario;
import modeloDAO.DAO;
import modeloDAO.DaoProntuarios;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author PC
 */
public class FormProntuários extends javax.swing.JFrame {

   
     
   
    
    public FormProntuários() {
        initComponents();
        listarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldCodProntuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPaciente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDiagnostico = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldExames = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldReceita = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxSituaçao = new javax.swing.JComboBox<>();
        jLabelLocalização = new javax.swing.JLabel();
        jTextFieldLocalizaçao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProntuario = new javax.swing.JTable();
        jButtonSalvar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonCarrCampos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Codigo Prontuário");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 130, 17);
        getContentPane().add(jTextFieldCodProntuario);
        jTextFieldCodProntuario.setBounds(140, 20, 70, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Paciente");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 20, 60, 17);
        getContentPane().add(jTextFieldPaciente);
        jTextFieldPaciente.setBounds(300, 20, 490, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Diagnostico");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 70, 90, 20);
        getContentPane().add(jTextFieldDiagnostico);
        jTextFieldDiagnostico.setBounds(310, 70, 460, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Exames");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(230, 120, 80, 20);
        getContentPane().add(jTextFieldExames);
        jTextFieldExames.setBounds(310, 120, 460, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Receitas");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 170, 60, 20);
        getContentPane().add(jTextFieldReceita);
        jTextFieldReceita.setBounds(310, 170, 450, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Situação do Prontuário");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 220, 140, 17);

        jComboBoxSituaçao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Ativo", "Inativo" }));
        getContentPane().add(jComboBoxSituaçao);
        jComboBoxSituaçao.setBounds(360, 220, 130, 20);

        jLabelLocalização.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelLocalização.setText("Localização");
        getContentPane().add(jLabelLocalização);
        jLabelLocalização.setBounds(210, 270, 90, 17);
        getContentPane().add(jTextFieldLocalizaçao);
        jTextFieldLocalizaçao.setBounds(310, 260, 240, 30);

        jTableProntuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo Prontuário", "Paciente", "Diagnostico", "Exames", "Receitas", "Situação", "Localização"
            }
        ));
        jScrollPane1.setViewportView(jTableProntuario);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 310, 850, 230);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(10, 80, 120, 23);

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlterar);
        jButtonAlterar.setBounds(10, 120, 120, 23);

        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(Excluir);
        Excluir.setBounds(10, 160, 120, 23);

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(10, 200, 120, 23);

        jButtonCarrCampos.setText("Carregar Campos");
        jButtonCarrCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarrCamposActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCarrCampos);
        jButtonCarrCampos.setBounds(10, 240, 150, 23);

        setSize(new java.awt.Dimension(868, 588));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        BeansProntuario pront = new BeansProntuario();
        pront.setCodProntuario(Integer.parseInt(jTextFieldCodProntuario.getText()));
        pront.setNomePaciente(jTextFieldPaciente.getText());
        pront.setDiagnostico(jTextFieldDiagnostico.getText());
        pront.setExame(jTextFieldExames.getText());
        pront.setReceita(jTextFieldReceita.getText());
        pront.setSituaçao((String) jComboBoxSituaçao.getSelectedItem());
        pront.setLocalização(jTextFieldLocalizaçao.getText());

        
        DaoProntuarios prontDao = new DaoProntuarios();
        prontDao.salvar(pront);
        JOptionPane.showMessageDialog(this, "Salvo");
        
        listarTabela();
        limparCampos();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        BeansProntuario pront = new BeansProntuario();
        pront.setCodProntuario(Integer.parseInt(jTextFieldCodProntuario.getText()));
        pront.setNomePaciente(jTextFieldPaciente.getText());
        pront.setDiagnostico(jTextFieldDiagnostico.getText());
        pront.setExame(jTextFieldExames.getText());
        pront.setReceita(jTextFieldReceita.getText());
        pront.setSituaçao((String) jComboBoxSituaçao.getSelectedItem());
        pront.setLocalização(jTextFieldLocalizaçao.getText());

        
        DaoProntuarios prontDao = new DaoProntuarios();
        prontDao.alterar(pront);
        JOptionPane.showMessageDialog(this, "Alterado");
        
        listarTabela();
        limparCampos();
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
       int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir??", "Confirma Exclusão", JOptionPane.YES_NO_OPTION);
       
       if (resposta == 0){
        BeansProntuario pront = new BeansProntuario();
        pront.setCodProntuario(Integer.parseInt(jTextFieldCodProntuario.getText()));
        
        DaoProntuarios prontDao = new DaoProntuarios();
        prontDao.excluir(pront);
        JOptionPane.showMessageDialog(this, "Excluido");
       }
        
        listarTabela();
        limparCampos();
    }//GEN-LAST:event_ExcluirActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
         String nome = jTextFieldPaciente.getText();
         this.listarTabelaNome(nome);
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonCarrCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarrCamposActionPerformed
        CarregarCampos();
    }//GEN-LAST:event_jButtonCarrCamposActionPerformed
    
    
    
    
    
    public void listarTabelaNome(String nome){
      
       DefaultTableModel val = (DefaultTableModel) jTableProntuario.getModel();
       val.getDataVector().removeAllElements();
       DaoProntuarios prontDao = new DaoProntuarios();
       List <BeansProntuario> prontuario = prontDao.pesquisarProntuarios(nome);
       int i = 0;
       while(prontuario.size() > i){
           
       val.addRow(new Object[] {prontuario.get(i).getCodProntuario(), prontuario.get(i).getNomePaciente(), prontuario.get(i).getDiagnostico(), prontuario.get(i).getExame(),prontuario.get(i).getReceita(), prontuario.get(i).getSituaçao(), prontuario.get(i).getLocalização()});
       i++;
       }
    }    
    
    public void listarTabela(){
      
       DefaultTableModel val = (DefaultTableModel) jTableProntuario.getModel();
       val.getDataVector().removeAllElements();
       DaoProntuarios prontDao = new DaoProntuarios();
       List <BeansProntuario> prontuario = prontDao.listarProntuarios();
       int i = 0;
       while(prontuario.size() > i){
           
       val.addRow(new Object[] {prontuario.get(i).getCodProntuario(), prontuario.get(i).getNomePaciente(), prontuario.get(i).getDiagnostico(), prontuario.get(i).getExame(),prontuario.get(i).getReceita(), prontuario.get(i).getSituaçao(), prontuario.get(i).getLocalização()});
       i++;
       }
    } 
    
    public void limparCampos(){
        jTextFieldCodProntuario.setText("");
        jTextFieldPaciente.setText("");
        jTextFieldDiagnostico.setText("");
        jTextFieldExames.setText("");
        jTextFieldReceita.setText("");
        jComboBoxSituaçao.setSelectedItem("Selecione");
        jTextFieldLocalizaçao.setText("");
    }
    
    public void CarregarCampos(){
        int setar = jTableProntuario.getSelectedRow();
        
        jTextFieldCodProntuario.setText(jTableProntuario.getModel().getValueAt(setar, 0).toString());
        jTextFieldPaciente.setText(jTableProntuario.getModel().getValueAt(setar, 1).toString());
        jTextFieldDiagnostico.setText(jTableProntuario.getModel().getValueAt(setar, 2).toString());
        jTextFieldExames.setText(jTableProntuario.getModel().getValueAt(setar, 3).toString());
        jTextFieldReceita.setText(jTableProntuario.getModel().getValueAt(setar, 4).toString());
        jComboBoxSituaçao.setSelectedItem(jTableProntuario.getModel().getValueAt(setar, 5).toString());
        jTextFieldLocalizaçao.setText(jTableProntuario.getModel().getValueAt(setar, 6).toString());
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProntuários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProntuários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProntuários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProntuários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormProntuários().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Excluir;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCarrCampos;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxSituaçao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelLocalização;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProntuario;
    private javax.swing.JTextField jTextFieldCodProntuario;
    private javax.swing.JTextField jTextFieldDiagnostico;
    private javax.swing.JTextField jTextFieldExames;
    private javax.swing.JTextField jTextFieldLocalizaçao;
    private javax.swing.JTextField jTextFieldPaciente;
    private javax.swing.JTextField jTextFieldReceita;
    // End of variables declaration//GEN-END:variables
}
