/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.beans.BeansConsulta;
import modeloDAO.DaoConsulta;

/**
 *
 * @author PC
 */
public class FormConsultas extends javax.swing.JFrame {

    /**
     * Creates new form FormConsultas
     */
    public FormConsultas() {
        initComponents();
        listarTabelaConsultas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelPaciente = new javax.swing.JLabel();
        jTextFieldPaciente = new javax.swing.JTextField();
        jComboBoxMedico = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jTextFieldData = new javax.swing.JTextField();
        jTextFieldHora = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsultas = new javax.swing.JTable();
        jLabelCodConsulta = new javax.swing.JLabel();
        jTextFieldCodConsulta = new javax.swing.JTextField();
        jButtonCarrCampos = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Consultas Agendadas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(281, 11, 150, 20);

        jLabelPaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPaciente.setText("Paciente");
        getContentPane().add(jLabelPaciente);
        jLabelPaciente.setBounds(160, 100, 60, 17);
        getContentPane().add(jTextFieldPaciente);
        jTextFieldPaciente.setBounds(230, 90, 400, 30);

        jComboBoxMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Adriane Gomes", "João Silva", "Maria Sousa", "Lucas Matos", "Marta Oliveira", "Lucas Souza" }));
        jComboBoxMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxMedico);
        jComboBoxMedico.setBounds(250, 150, 130, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Médico");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 150, 50, 20);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(10, 43, 100, 30);

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlterar);
        jButtonAlterar.setBounds(10, 83, 100, 30);

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(10, 123, 100, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Data");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 220, 40, 17);

        jLabelHora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelHora.setText("Hora");
        getContentPane().add(jLabelHora);
        jLabelHora.setBounds(420, 210, 29, 20);
        getContentPane().add(jTextFieldData);
        jTextFieldData.setBounds(240, 210, 140, 30);
        getContentPane().add(jTextFieldHora);
        jTextFieldHora.setBounds(460, 210, 130, 30);

        jTableConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código Consulta", "Paciente ", "Médico ", "Data", "Hora"
            }
        ));
        jScrollPane1.setViewportView(jTableConsultas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 280, 660, 240);

        jLabelCodConsulta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCodConsulta.setText("Código Consulta");
        getContentPane().add(jLabelCodConsulta);
        jLabelCodConsulta.setBounds(140, 60, 110, 17);
        getContentPane().add(jTextFieldCodConsulta);
        jTextFieldCodConsulta.setBounds(260, 50, 80, 30);

        jButtonCarrCampos.setText("Carregar Campos");
        jButtonCarrCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarrCamposActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCarrCampos);
        jButtonCarrCampos.setBounds(0, 210, 140, 30);

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(10, 163, 100, 30);

        setSize(new java.awt.Dimension(706, 596));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        BeansConsulta con = new BeansConsulta();
        
        con.setCodConsulta(Integer.parseInt(jTextFieldCodConsulta.getText()));
        con.setNomePaciente(jTextFieldPaciente.getText());
        con.setMedico((String) jComboBoxMedico.getSelectedItem());
        con.setData(jTextFieldData.getText());
        con.setHora(jTextFieldHora.getText());
        
        DaoConsulta conDao = new DaoConsulta();
        conDao.alterar(con);
        JOptionPane.showMessageDialog(this, "Alterado");
        
        listarTabelaConsultas();
        limparCampos();
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        BeansConsulta con = new BeansConsulta();
        
        con.setCodConsulta(Integer.parseInt(jTextFieldCodConsulta.getText()));
        con.setNomePaciente(jTextFieldPaciente.getText());
        con.setMedico((String) jComboBoxMedico.getSelectedItem());
        con.setData(jTextFieldData.getText());
        con.setHora(jTextFieldHora.getText());
        
        DaoConsulta conDao = new DaoConsulta();
        conDao.salvar(con);
        JOptionPane.showMessageDialog(this, "Salvo");
        
        listarTabelaConsultas();
        limparCampos();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir??", "Confirma Exclusão", JOptionPane.YES_NO_OPTION);
        
      if (resposta == 0) {
        BeansConsulta con = new BeansConsulta();
        con.setCodConsulta(Integer.parseInt(jTextFieldCodConsulta.getText()));
       
        DaoConsulta conDao = new DaoConsulta();
        conDao.excluir(con);
        JOptionPane.showMessageDialog(this, "Deletado");
      }
        listarTabelaConsultas();
        limparCampos();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonCarrCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarrCamposActionPerformed
        carregarCampos();
    }//GEN-LAST:event_jButtonCarrCamposActionPerformed

    private void jComboBoxMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMedicoActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        String nome = jTextFieldPaciente.getText();
        this.listarTabelaNomes(nome);
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    public void listarTabelaConsultas(){
      
       DefaultTableModel val = (DefaultTableModel) jTableConsultas.getModel();
       val.getDataVector().removeAllElements();
       DaoConsulta conDao = new DaoConsulta();
       List <BeansConsulta> usuario = conDao.listarConsultas();
       int i = 0;
       while(usuario.size() > i){
           
       val.addRow(new Object[] {usuario.get(i).getCodConsulta(),  usuario.get(i).getNomePaciente(), usuario.get(i).getMedico(), usuario.get(i).getData(), usuario.get(i).getHora()});
       i++;
       }
    } 
    
    public void listarTabelaNomes(String nome){
      
       DefaultTableModel val = (DefaultTableModel) jTableConsultas.getModel();
       val.getDataVector().removeAllElements();
       DaoConsulta conDao = new DaoConsulta();
       List <BeansConsulta> usuario = conDao.pesquisarConsultas(nome);
       int i = 0;
       while(usuario.size() > i){
           
       val.addRow(new Object[] {usuario.get(i).getCodConsulta(),  usuario.get(i).getNomePaciente(), usuario.get(i).getMedico(), usuario.get(i).getData(), usuario.get(i).getHora()});
       i++;
       }
    } 
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormConsultas().setVisible(true);
            }
        });
    }
    
    public void limparCampos(){
        
        jTextFieldCodConsulta.setText("");
        jTextFieldPaciente.setText("");
        jComboBoxMedico.setSelectedItem("Selecione");
        jTextFieldData.setText("");
        jTextFieldHora.setText("");
        
    }
    
    public void carregarCampos(){
        int setar = jTableConsultas.getSelectedRow();
        
        jTextFieldCodConsulta.setText(jTableConsultas.getModel().getValueAt(setar, 0).toString());
        jTextFieldPaciente.setText(jTableConsultas.getModel().getValueAt(setar, 1).toString());
        jComboBoxMedico.setSelectedItem(jTableConsultas.getModel().getValueAt(setar, 2).toString());
        jTextFieldData.setText(jTableConsultas.getModel().getValueAt(setar, 3).toString());
        jTextFieldHora.setText(jTableConsultas.getModel().getValueAt(setar, 4).toString());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCarrCampos;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxMedico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCodConsulta;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelPaciente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsultas;
    private javax.swing.JTextField jTextFieldCodConsulta;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldHora;
    private javax.swing.JTextField jTextFieldPaciente;
    // End of variables declaration//GEN-END:variables
}
