/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaAcesso
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCadMedico = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonCadPacientes = new javax.swing.JButton();
        jButtonCadUsuarios = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonCadConsultas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonCadProntuários = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemMedicos = new javax.swing.JMenuItem();
        jMenuItemPacientes = new javax.swing.JMenuItem();
        jMenuItemUsuarios = new javax.swing.JMenuItem();
        jMenuItemConsultas = new javax.swing.JMenuItem();
        jMenuItemProntuarios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Principal");
        getContentPane().setLayout(null);

        jButtonCadMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Imagens/IconeMedico.jpeg"))); // NOI18N
        jButtonCadMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadMedico);
        jButtonCadMedico.setBounds(20, 180, 130, 150);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Médicos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 150, 60, 20);

        jButtonCadPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Imagens/IconePacienteUpDate.jpeg"))); // NOI18N
        jButtonCadPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadPacientes);
        jButtonCadPacientes.setBounds(180, 180, 130, 150);

        jButtonCadUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Imagens/IconeUsuarioUpDate.jpeg"))); // NOI18N
        jButtonCadUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadUsuarios);
        jButtonCadUsuarios.setBounds(330, 180, 130, 150);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Pacientes");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 150, 60, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Usuários");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(330, 150, 60, 17);

        jButtonCadConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Imagens/IconeAgendaUpDate.jpeg"))); // NOI18N
        jButtonCadConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadConsultasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadConsultas);
        jButtonCadConsultas.setBounds(480, 180, 130, 150);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Consultas");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(480, 150, 60, 17);

        jButtonCadProntuários.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Imagens/icone_prontuario.jpg"))); // NOI18N
        jButtonCadProntuários.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadProntuáriosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadProntuários);
        jButtonCadProntuários.setBounds(630, 180, 130, 150);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Prontuários");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(630, 140, 70, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setText("Bem Vindo");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(300, 20, 180, 30);

        jMenu1.setText("Cadastros");

        jMenuItemMedicos.setText("Medicos");
        jMenuItemMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMedicosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemMedicos);

        jMenuItemPacientes.setText("Pacientes");
        jMenuItemPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPacientesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemPacientes);

        jMenuItemUsuarios.setText("Usuários");
        jMenuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUsuarios);

        jMenuItemConsultas.setText("Consultas");
        jMenuItemConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultasActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemConsultas);

        jMenuItemProntuarios.setText("Prontuários");
        jMenuItemProntuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProntuariosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemProntuarios);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemSair);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(863, 502));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPacientesActionPerformed
      FormPaciente tela = new FormPaciente();
      tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemPacientesActionPerformed

    private void jMenuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuariosActionPerformed
       FormUsuario tela = new FormUsuario();
       tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemUsuariosActionPerformed

    private void jButtonCadMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadMedicoActionPerformed
       FormMedico tela = new FormMedico();
       tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadMedicoActionPerformed

    private void jButtonCadPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadPacientesActionPerformed
      FormPaciente tela = new FormPaciente();
      tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadPacientesActionPerformed

    private void jButtonCadUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadUsuariosActionPerformed
       FormUsuario tela = new FormUsuario();
       tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadUsuariosActionPerformed

    private void jButtonCadConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadConsultasActionPerformed
       FormConsultas tela = new FormConsultas();
       tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadConsultasActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja Realmente sair?", "Confirma saída", JOptionPane.YES_NO_OPTION);
        
        if (resposta ==0){
           System.exit(0);
        }
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jButtonCadProntuáriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadProntuáriosActionPerformed
      FormProntuários tela = new FormProntuários();
      tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadProntuáriosActionPerformed

    private void jMenuItemMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMedicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemMedicosActionPerformed

    private void jMenuItemConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultasActionPerformed
       FormConsultas tela = new FormConsultas();
       tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultasActionPerformed

    private void jMenuItemProntuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProntuariosActionPerformed
      FormProntuários tela = new FormProntuários();
      tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemProntuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadConsultas;
    private javax.swing.JButton jButtonCadMedico;
    private javax.swing.JButton jButtonCadPacientes;
    private javax.swing.JButton jButtonCadProntuários;
    private javax.swing.JButton jButtonCadUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemConsultas;
    private javax.swing.JMenuItem jMenuItemMedicos;
    private javax.swing.JMenuItem jMenuItemPacientes;
    private javax.swing.JMenuItem jMenuItemProntuarios;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemUsuarios;
    // End of variables declaration//GEN-END:variables
}
